### ISSUE TITLE
typo: convenvionalcommits

### ISSUE THREAD

**Issue by jschenz-chwy** [luabida/semantic-release-pr-title-check#28]
https://github.com/osl-incubator/semantic-release-pr-title-check/blob/85c2ded001e6947d84a9d72252ddaa42e2e430e5/src/linter.ts#LL47C68-L47C68

Instead of `convenvionalcommits` it should read `conventionalcommits`.

**Comment by xmnlab** [comment]
hi @jschenz-chwy , thanks for reporting that.
do you mind opening open a PR that?

thank you
